security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
